#!/bin/bash
#*******************************************************************************
# ALMA - Atacama Large Millimiter Array
# Copyright (c) National Astronomical Observatory of Japan, 2017 
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#

#
# This is the wrapper script to launch BulkDataNTOneFlowPerformanceTest
# implemented in Java.
#

# TODO: launch receiver in a separate thread, and check if the data sent
#       from this sender can be correctly received.

# "-ea" flag enables the assertion. Because this program is supposed to be
# used by a developer, not in ALMA operation, this script enables the
# assertion.
JVM_FLAGS="${JVM_FLAGS} -ea"

# TODO: do not override the log file
JVM_FLAGS="${JVM_FLAGS} -XX:+UseParallelOldGC -Xms1024m -Xmx1024m -Xlog:gc*:bulkDataNTOneFlowPerformanceTest.log:time,level,tags:filecount=5"

# Main class of 
MAIN_CLASS=alma.acs.bulkdata.BulkDataNTOneFlowPerformanceTest
acsStartJava -jvmFlags "${JVM_FLAGS}" ${MAIN_CLASS} "$@"
