#! /bin/bash
#*************************************************************************
# ALMA - Atacama Large Millimiter Array
# (c) European Southern Observatory, 2002
# Copyright by ESO (in the framework of the ALMA collaboration),
# All rights reserved
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA 02111-1307  USA
#

# Now I look for the ACSError.xsd file
if [ "X$2" == "X" ]; then
   result=$(searchFile /idl/ACSError.xsd)
   if [ "$result" != "#error#" ]; then
      ERROR_SCHEMA=$result/idl/ACSError.xsd
   else
      echo "/idl/ACSError.xsd couldn't be found."
      exit 1
	fi
else
   if [ -f $2 ]; then
      ERROR_SCHEMA=$2
   else
      echo "/idl/ACSError.xsd couldn't be found."
      exit 1
   fi
fi

if [ "X$3" == "X" ]; then
	result=$(searchFile lib/xmlvalidator.jar)
   if [ "$result" != "#error#" ]; then
	   CLP=$result/lib/xmlvalidator.jar
   else
		echo "xmlvalidator.jar was not found in ACSROOT/INTLIST/INTROOT"
	fi
else
	if [ -f $3 ]; then
		CLP=$3
	fi
fi
## Here I validate the Error Definition XML file
echo "java -cp \"$CLP\" alma.acs.xml.validator.XMLValidator $1 $ERROR_SCHEMA"
java -cp "$CLP" alma.acs.xml.validator.XMLValidator $1 $ERROR_SCHEMA
exit $?
