#! /bin/bash
#*************************************************************************
# ALMA - Atacama Large Millimiter Array
# (c) European Southern Observatory, 2002
# Copyright by ESO (in the framework of the ALMA collaboration),
# All rights reserved
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA 02111-1307  USA
#

if [ "X$4" != "X" ]; then
	mod=$4
else
	mod=..
fi

if [ "X$5" != "X" ]; then
	xalan_path=$5
else
	xalan_path=$(searchFile lib/xalan-2.7.3.jar)/lib/xalan-2.7.3.jar
fi

if [ "X$6" != "X" ]; then
	xalanser_path=$6
else
	xalanser_path=$(searchFile lib/serializer-2.7.3.jar)/lib/serializer-2.7.3.jar
fi

if [ -f $mod/config/AES2CPP.xslt ]
then
   CPP_XSLT=$mod/config/AES2CPP.xslt
else
   # Now I look for in the other dirs
   result=$(searchFile config/AES2CPP.xslt)
   if [ "$result" != "#error#" ]
   then
      CPP_XSLT=$result/config/AES2CPP.xslt
   fi
fi

if [ -f $mod/config/AES2H.xslt ]
then
   H_XSLT=$mod/config/AES2H.xslt
else
   # Now I look for in the other dirs
   result=$(searchFile config/AES2H.xslt)
   if [ "$result" != "#error#" ]
   then
      H_XSLT=$result/config/AES2H.xslt
   fi
fi

java -cp "${xalan_path}${PATH_SEP}${xalanser_path}" org.apache.xalan.xslt.Process -XSL $CPP_XSLT -IN $1 -OUT $2
java -cp "${xalan_path}${PATH_SEP}${xalanser_path}" org.apache.xalan.xslt.Process -XSL $H_XSLT -IN $1 -OUT $3
