#! /bin/sh
. acsstartupAcsPorts
#
# We pass down also any other command line parameter, assumed to be given as 
# Java VM configuration parameters.
# The most important is 
#    -Dobjexp.pool_timeout=<time in ms>
# to set DSI pool timeout.
# To run objexp in intrusive way you can set non-sticky mode at startup using
#    -Dobjexp.connect_non_sticky=false
# Now the default is non-sticky mode. 
export HOST=`getIP`

acsStartJava \
    -noClassLoader -noAutoClasspath -addToClasspath pfl-basic-4.1.2.jar:jchart2d-3.3.2.jar:acsGUIutil.jar:acscommon.jar:acscomponent.jar:acserr.jar:acserrj.jar:ACSErrTypeCommon.jar:acsjlog.jar:acstime.jar:baci.jar:castor-1.4.1-acs.jar:cdbErrType.jar:jACSUtil.jar:logging_idl.jar:maci.jar:maciErrType.jar:maciSchemaBindings.jar:objexpErrType.jar:oe.jar:slf4j-acs.jar:slf4j-api-1.7.32.jar:repeatGuard.jar \
    $* -DOAIAddr=$HOST si.ijs.acs.objectexplorer.ObjectExplorer BACI 
