#! /bin/bash
#*************************************************************************
# ALMA - Atacama Large Millimiter Array
# (c) European Southern Observatory, 2002
# Copyright by ESO (in the framework of the ALMA collaboration),
# All rights reserved
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
# MA 02111-1307  USA
#

if [ "X$3" != "X" ]; then
	mod=$3
else
	mod=..
fi

if [ "X$4" != "X" ]; then
	xalan_path=$4
else
	xalan_path=$(searchFile lib/xalan-2.7.3.jar)/lib/xalan-2.7.3.jar
fi

if [ "X$5" != "X" ]; then
	xalanser_path=$5
else
	xalanser_path=$(searchFile lib/serializer-2.7.3.jar)/lib/serializer-2.7.3.jar
fi

if [ -f $mod/config/LTS2Py.xslt ]
then
   PY_XSLT=$mod/config/LTS2Py.xslt
else
   # Now I look for in the other dirs
   result=$(searchFile config/LTS2Py.xslt)
   if [ "$result" != "#error#" ]
   then
      PY_XSLT=$result/config/LTS2Py.xslt
   fi
fi
java -cp "${xalan_path}${PATH_SEP}${xalanser_path}" org.apache.xalan.xslt.Process -XSL $PY_XSLT -IN $1 -OUT $2
