version: "3.4"

x-args: &args
   USER_NAME: ${USER_NAME}
   GROUP_NAME: ${GROUP_NAME}
   USER_ID: ${USER_ID}
   GROUP_ID: ${GROUP_ID}

x-env: &env
   - DISPLAY=${DISPLAY}

x-volumes: &volumes
   - ${REPO_DIR}:/Repos:z
   - ${ALMA_DIR}/${CONTAINER_DIR}:/alma:z
   - ${HOME_DIR}/${CONTAINER_DIR}:/home/${USER_NAME}:z
   - /tmp/.X11-unix:/tmp/.X11-unix:z

x-acs-images: &common
   build:
      dockerfile: Dockerfile
      context: ./${IMAGE_OS}
      args:
         *args
   security_opt:
      - seccomp:unconfined
   image: acsdev-${IMAGE_OS}
   container_name: acsdev_${IMAGE_OS}_run
   environment:
      *env
   volumes:
      *volumes
   working_dir: /home/${USER_NAME}
   ulimits:
      nproc: 62424
      nofile:
         soft: 64000
         hard: 524288
   dns:
     - 8.8.8.8
     - 4.4.4.4
   networks:
    - acs-docker
   extra_hosts:
      - acs:127.0.1.1
   hostname: acs
   container_name: acs_${IMAGE_OS}

services:
   centos6:
      <<: *common
   centos7:
      <<: *common
   centos8:
      <<: *common

networks:
   acs-docker:
      driver: bridge
