#*******************************************************************************

# ALMA - Atacama Large Millimiter Array
#
# "@(#) $Id: Makefile,v 1.23 2012/01/21 22:48:11 tstaig Exp $" 
#
# Makefile of ........
#
#

#*******************************************************************************
# This Makefile follows ACS Standards (see Makefile(5) for more).
#*******************************************************************************
# REMARKS
#    None
#-------------------------------------------------------------------------------
-include rules.mk

#
#>>>>> END OF standard rules

#
# CHOSE PLATFORM
# --------------
# Default is UNIX, for VxVorks application next line MUST BE UNCOMMENTED
#MAKE_VXWORKS = on   

#
# INCLUDE STANDARDS
# -----------------


MAKEDIRTMP := $(shell searchFile include/acsMakefile)
ifneq ($(MAKEDIRTMP),\#error\#)
   MAKEDIR := $(MAKEDIRTMP)/include
   include $(MAKEDIR)/acsMakefile
endif


#
# TARGETS
# -------
all: do_all
	@echo " . . . 'all' done" 

clean: clean_all
	$(RM) *~ ../include/*~ ../idl/*~ ../*~ ../../*~ ../doc/html/* core
	$(RM) tmp.txt 
	@echo " . . . clean done"

clean_dist: clean clean_dist_all
	@echo " . . . clean_dist done"

man: do_man
	@echo " . . . man page(s) done"

install:
	@echo " . . . no installation to be done for this test module"

deploy:
	@echo " . . . no deployment to be done for this test module"
