#! /bin/bash

function printUsage {
    echo "xjc wrapper Help Screen"
    echo ""
    echo "This script is a Wrapper of the xjc command line."
    echo "Supported Flags:"
    echo "      --whelp       Show this help"
    echo "      --activation  activation jar path"
    echo "      --api         jaxb-api jar path"
    echo "      --core        jaxb-core jar path"
    echo "      --impl        jaxb-impl jar path"
    echo "      --xjc         jaxb-xjc jar path"
    echo "      --istack      istack-commons jar path"
    echo "      --params      xjc parameters"
    echo ""
}

while test $# -gt 0; do
    case $1 in
      --whelp)
        printUsage
        exit 0
        ;;
      --activation)
        ACTIVATION_API=$2
        shift 2
        ;;
      --api)
        JAXB_API=$2
        shift 2
        ;;
      --core)
        JAXB_CORE=$2
        shift 2
        ;;
      --impl)
        JAXB_XJC=$2
        shift 2
        ;;
      --xjc)
        JAXB_XJC=$2
        shift 2
        ;;
      --istack)
        ISTACK_COMMONS=$2
        shift 2
        ;;
      --params)
        shift
        break
        ;;
      *)
        break
        ;;
    esac
done

XJC_PARS=$@

if [[ -z $ACTIVATION_API || ! -f $ACTIVATION_API ]]; then
   # Now I look for in the other dirs
   result=$(searchFile "lib/jakarta.activation-api-*.jar")
   if [ "$result" != "#error#" ]
   then
      ACTIVATION_API=$(ls $result/lib/jakarta.activation-api-*.jar)
   fi
fi

if [[ -z $JAXB_API || ! -f $JAXB_API ]]; then
   # Now I look for in the other dirs
   result=$(searchFile "lib/jakarta.xml.bind-api-*.jar")
   if [ "$result" != "#error#" ]
   then
      JAXB_API=$(ls $result/lib/jakarta.xml.bind-api-*.jar)
   fi
fi

if [[ -z $JAXB_CORE || ! -f $JAXB_CORE ]]; then
   # Now I look for in the other dirs
   result=$(searchFile "lib/jaxb-core-*.jar")
   if [ "$result" != "#error#" ]
   then
      JAXB_CORE=$(ls $result/lib/jaxb-core-*.jar)
   fi
fi

if [[ -z $JAXB_IMPL || ! -f $JAXB_IMPL ]]; then
   # Now I look for in the other dirs
   result=$(searchFile "lib/jaxb-impl-*.jar")
   if [ "$result" != "#error#" ]
   then
      JAXB_IMPL=$(ls $result/lib/jaxb-impl-*.jar)
   fi
fi

if [[ -z $JAXB_XJC || ! -f $JAXB_XJC ]]; then
   # Now I look for in the other dirs
   result=$(searchFile "lib/jaxb-xjc-*.jar")
   if [ "$result" != "#error#" ]
   then
      JAXB_XJC=$(ls $result/lib/jaxb-xjc-*.jar)
   fi
fi

if [[ -z $ISTACK_COMMONS || ! -f $ISTACK_COMMONS ]]; then
   # Now I look for in the other dirs
   result=$(searchFile "lib/istack-commons-runtime-*.jar")
   if [ "$result" != "#error#" ]
   then
      ISTACK_COMMONS=$(ls $result/lib/istack-commons-runtime-*.jar)
   fi
fi

echo $JAVA_HOME/bin/java -cp $ACTIVATION_API$PATH_SEP$JAXB_API$PATH_SEP$JAXB_CORE$PATH_SEP$JAXB_IMPL$PATH_SEP$JAXB_XJC$PATH_SEP$ISTACK_COMMONS com.sun.tools.xjc.XJCFacade $XJC_PARS
$JAVA_HOME/bin/java -cp $ACTIVATION_API$PATH_SEP$JAXB_API$PATH_SEP$JAXB_CORE$PATH_SEP$JAXB_IMPL$PATH_SEP$JAXB_XJC$PATH_SEP$ISTACK_COMMONS com.sun.tools.xjc.XJCFacade $XJC_PARS
