#!/bin/bash 
#
# Script to automatically install Ant
#
# who       when       what
# --------  ---------  ----------------------------------------------
# psivera   24/04/2003 created
# sturolla  09/09/2005 ported to Bourne Shell and OS checks is done by an external subroutine
# hsommer   08/07/2007 Update to ANT 1.7 for ACS 7.0
#
# Load functions
. standardUtilities
#
# Fetch operating system and release version
#
os_discovery

# Some default values
#
CURR_DIR=pwd
INSTDIR=$ALMASW_INSTDIR/swig
SWIG_VERSION=3.0.12
PCRE_VERSION=8.41
SRCFILE=CURR_DIR/../PRODUCTS/swig-SWIG_VERSION.tar.gz

Install_swig()
{
    if [ -z "$INSTDIR" ]
    then
        echo "INSTDIR is not set, cannot continue.\n"
        exit 1
    fi

    if [ -d $INSTDIR ]
    then
      echo $INSTDIR directory exists already.Cleaning it up.
      rm -rf $INSTDIR
    fi
    mkdir $INSTDIR

    if [ ! -d $INSTDIR ]
    then
        mkdir -p $INSTDIR
        RET=$?
        if [ $RET -ne 0 ]
        then
            echo "Failed to create $ALMASW_INSTDIR/swig, cannot continue..."
            exit 1
        fi
    fi
    
    echo "unpacking swig $SWIG_VERSION... \c"
    cd $CURR_DIR/../PRODUCTS/
    tar xzf swig-$SWIG_VERSION.tar.gz
    cp pcre-$PCRE_VERSION.tar.bz2 ./swig-$SWIG_VERSION/
    cd swig-$SWIG_VERSION
    ./Tools/pcre-build.sh
    ./configure --prefix=$INSTDIR LIBS=-lstdc++
    make 
    make install
   
    echo "done.\n"


}



######################################################################
#                                                                    #
# Execution starts here!                                             #
#                                                                    #
######################################################################

LOG=buildSwig.log
#
exec > $LOG 2>&1

date

CURR_DIR=`pwd`

#
# Check if a proper version of Swig is available in the O.S.
#
HAVE_SWIG=$(which swig 2> /dev/null)
if [ "$HAVE_SWIG" != "" ]; then
    SWIG_OS=$(swig -version 2> /dev/null |grep Version|cut -d " " -f 3)
    SWIG_MIN=$(echo "$SWIG_VERSION $SWIG_OS" |xargs -n1 |sort -V |head -n1)
fi

#
# It build and install the archive
#
if [[ "$SWIG_MIN" == "$SWIG_VERSION" && ! -e "$ALMASW_INSTDIR/swig" ]]; then
    echo "Skipping Swig build because swig $SWIG_OS is available in the operating system."
else
    Install_swig
fi

cd $CURR_DIR

echo swig installation done!
date
